runmode: release               # 开发模式, debug, release, test 部署时环境变量覆盖
addr: :4096                  # HTTP绑定端口
name: yoyo-mall              # API Server的名字
url: http://127.0.0.1:4096   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: sdalfjdlsaiyoyoasdjmallsdlfajlsa
db:  # DB 配置 部署时环境变量覆盖
  name: yoyo-mall
  addr: 127.0.0.1:3306
  username: root
  password: root
oss:
  access_key:
  secret_key:
  bucket_name:
  domain_name:
redis:
  addr: 127.0.0.1:6379
  password: ""
